### ISSUE TITLE
Add timestamp to comment

### ISSUE THREAD

**Issue by cameron-toy** [jupytercalpoly/jupyterlab-chat#16]
<img width="867" alt="image" src="https://user-images.githubusercontent.com/38936057/123885212-d368fd80-d901-11eb-9dda-c1890459cbf0.png">

As seen above, the comment should have a human-readable timestamp beneath the username.

The timestamp will have to be stored in the metadata so the `IComment` type will have to be amended.

**Comment by nairrrahul** [comment]
Resolved in #21
