### ISSUE TITLE
Binder broken?

### ISSUE THREAD

**Issue by cab938** [jupytercalpoly/jupyterlab-chat#7]
I tried to check out whats in binder but alas, it seems broken....

![image](https://user-images.githubusercontent.com/1355641/122987168-499fba00-d36e-11eb-9327-61482eb3fcb1.png)

**Comment by cameron-toy** [comment]
I think that's because the JupyterLab version required in binder/environment.yml is incorrect. I'll update and see if that fixes it.

**Comment by cameron-toy** [comment]
I just checked and unfortunately Binder doesn't seem to provide the 3.1.0a13 release of JupyterLab required by the extension. I think we'll have to wait until an official 3.1 release before the Binder works.

**Comment by cab938** [comment]
I think it would be good to remove broken things. Just nuke all the binder stuff if it doesn't work with the repo, and keep the head of the repo always in working condition. Think of this as your final document of a press release - it should be coherent in itself for someone to read, even if not perfect.

**Comment by cab938** [comment]
(I'm not much of a fan of cookiecutter because it generates things for you which don't work. E.g. if people shouldn't be installing this from pip yet, don't tell them they should in the readme.md)

**Comment by cameron-toy** [comment]
Good points. I removed the binder and pip install stuff and will re-add them once the binder is working and the extension is in pypi.
